Feature.hover
Belray-Ventec/geslub-platform-react-ui pull request #12
Opened 2022-09-02 21:29 UTC by QuesoCaliente

2022-09-02 21:42 UTC, ThomasBelrayDev requested changes

2022-09-02 21:42 UTC, ThomasBelrayDev commented on src/components/paginator/paginator.module.css
> +:root {
La idea de ocupar las variables para los colores es más para los los colores principales, y que deben ser globales, para poder re-utilizarlo en cada archivo.module.css, de esa forma le sacamos el máximo provecho

2022-09-02 22:20 UTC, QuesoCaliente commented on src/components/paginator/paginator.module.css
> +:root {
listo, ahora deberia estar mejor

2022-09-05 15:39 UTC, ThomasBelrayDev approved these changes

2022-09-05 15:40 UTC, merged